version : "3"
services:
  rust-owndb:
    container_name: rust-owndb
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - type: bind
        source: .
        target: /opt/rust-owndb
    working_dir: /opt/rust-owndb